### ISSUE TITLE
Clickable target is confusing

### ISSUE THREAD

**Issue by eliasmalik** [FACG2/CodeBytesToDO#23]
You have button elements which are clickable to delete todos and mark them done. But the button elements are different sizes from the icons that are displayed:

<img width="64" alt="screen shot 2017-07-20 at 08 31 49" src="https://user-images.githubusercontent.com/12719553/28401998-148affda-6d26-11e7-8046-9aa47f64d666.png">

This means that I cannot click on the bottom half of the trash can, even though I would expect to be able to. Try to ensure your icons and your clickable targets are of similar sizes so that your users can interact with your site without thinking too much.

**Comment by Qamar-93** [comment]
Done
